/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/keyboard/button/index.vue')['default']
    Decorate: typeof import('./src/components/decorate/index.vue')['default']
    Guide: typeof import('./src/components/guide/index.vue')['default']
    Keyboard: typeof import('./src/components/keyboard/index.vue')['default']
    Logo: typeof import('./src/components/logo/index.vue')['default']
    Matrix: typeof import('./src/components/matrix/index.vue')['default']
    Next: typeof import('./src/components/next/index.vue')['default']
    Number: typeof import('./src/components/number/index.vue')['default']
    Pause: typeof import('./src/components/pause/index.vue')['default']
    Point: typeof import('./src/components/point/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
