name: Build

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Install node        
        uses: actions/setup-node@v3
        with:
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Run Build
        run: pnpm run build

      - name: echo cname
        run: echo 'tetris.elonehoo.xyz' > dist/CNAME

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
